### ISSUE TITLE
Use SparseDiffTools with ADNLPModel?

### ISSUE THREAD

**Issue by evrenmturan** [JuliaSmoothOptimizers/ADNLPModels.jl#13]
Hi,
This looks like a nice and useful package :) Thanks for the work. I was wondering if it would be easy to use SparseDiffTools.jl in this package for e.g. Hessian calculations?
If it would be easy to implement could you point me in the right direction.

**Comment by abelsiqueira** [comment]
Hi @evrenmturan, thanks for the availability. @amontoison and @tmigot are working on a sparse Hessian variant. They are using ModelingToolkit, I believe. They might be able to tell if and how you can help.
