### ISSUE TITLE
Add documentation/test on manually providing sparsity pattern for Jacobian/Hessian

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/ADNLPModels.jl#193]
The functions that need to be overloaded are 
https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/blob/921f360fd967b4ffbb2b993e05bfce937729a979/src/ADNLPModels.jl#L24
and
https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/blob/921f360fd967b4ffbb2b993e05bfce937729a979/src/ADNLPModels.jl#L37

- [ ] test jacobian
- [ ] test hessian
- [ ] documentation

**Comment by amontoison** [comment]
Added in the release 0.8.5
