### ISSUE TITLE
Test Graphs.jl coloring algorithm

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/ADNLPModels.jl#204]
https://docs.juliahub.com/Graphs/VJ6vx/1.5.1/coloring/

**Comment by amontoison** [comment]
@gdalle Did you know that these routines were implemented?
Can I close the issue?

**Comment by gdalle** [comment]
I do know that they exist. However, they are all about the classic distance-1 coloring, and that's not what we need:

- For Jacobian coloring, you want a distance-2 coloring in a bipartite graph
- For Hessian coloring, you want a star coloring

My package SparseMatrixColorings.jl provides these more sophisticated options. Another advantage is that I handle the relevant graphs directly in terms of the adjacency matrices. For the bipartite graph I even have an efficient storage where I use the adjacency and its transpose. Neither Graphs.jl nor other packages like SimpleWeightedGraphs.jl offer that.
