### ISSUE TITLE
Bug with upgrade to SymbolicUtils release 1.6 and 1.7

### ISSUE THREAD

**Issue by jbcaillau** [JuliaSmoothOptimizers/ADNLPModels.jl#232]
Hi there; recent problem when calling `Ipopt` on an `ADNLModel`, which is what we do in [OptimalControl.jl](https://control-toolbox.org/docs/optimalcontrol/stable). Was working fine until last week, I would say (first ran into the problem one day ago). Attached is a snapshot of the error, seemingly connected to the sparsity pattern analysis of the Hessian by means of `Symbolics.jl` (and `SymbolicUtils`). The problem can be reproduced by running the basic example from `OptimalControl.jl` [here](https://control-toolbox.org).

![IMG_3135](https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/assets/62183989/abbee363-1e2b-48df-9125-aa37b3ecc16d)
![IMG_3136](https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/assets/62183989/5f3d1b65-a573-4754-bb4c-596dddd115e4)

**Comment by tmigot** [comment]
Added a 1.5 limit in #235 in the docs and test Project.toml, to be dropped as soon as we get back on track.
