### ISSUE TITLE
Replace ColPack with SparseMatrixColorings?

### ISSUE THREAD

**Issue by gdalle** [JuliaSmoothOptimizers/ADNLPModels.jl#237]
Hi there @amontoison and friends! It's me again, and I come bearing gifts :sunglasses:
My new package [SparseMatrixColorings.jl](https://github.com/gdalle/SparseMatrixColorings.jl) aims to be a pure-Julia reimplementation of [ColPack](https://github.com/CSCsw/ColPack). It does not yet have every functionality, but it has the essentials. In addition, it offers decompression algorithms, and the test suite is outrageously thorough. Would you be interested in trying it out as a replacement for [ColPack.jl](https://github.com/exanauts/ColPack.jl)?
I haven't yet run benchmarks because there are some things I don't understand about the ColPack.jl interface (see https://github.com/exanauts/ColPack.jl/issues/12 if @michel2323 wants to help), but I expect performance to be rather good.
As an alternative, we could try a full integration with [DifferentiationInterface.jl](https://github.com/gdalle/DifferentiationInterface.jl) as discussed in #229, but that might be a lot of change at once.

**Comment by amontoison** [comment]
It's fine to add SparseMatrixColorings here Guillaume but it will be great to have benchmarks if we replace colpack.jl.
We could support both to more easily do the benchmarks?

**Comment by amontoison** [comment]
@michel2323 We need you!

**Comment by gdalle** [comment]
I think I found the answer: https://github.com/exanauts/ColPack.jl/issues/12#issuecomment-2147837471

Bipartite coloring is not supported by ColPack.jl, even though it is the most efficient graph representation of Jacobian coloring problems. So I'll only be able to benchmark on Hessian coloring problems, which are symmetric. Let's see what that turns up

**Comment by gdalle** [comment]
Here are some benchmarks. For the range of parameters I've tested, SMC is uniformly better than ColPack.jl.
For the Jacobian benchmarks, the insane speedup is probably due to the construction of a column adjacency grah instead of the natural row-column bipartite graph. It's bad because the adjacency graph is much denser than the bipartite graph. 

![image](https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/assets/22795598/0c88f820-c9f7-4dad-a246-16179c3dbb98)

![image](https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/assets/22795598/9401f817-cc46-4d7b-be87-7aa4b9f4e4f6)

**Comment by gdalle** [comment]
With our latest changes in https://github.com/exanauts/ColPack.jl/pull/20, here's what I get for the Jacobian coloring of random sparse matrices.

Note that this comparison is done with the natural order on vertices. ColPack is still better than SMC for custom orders (it has more of them and probably will compute them faster even once https://github.com/gdalle/SparseMatrixColorings.jl/pull/18 is merged).

![image](https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/assets/22795598/482a2c1e-424f-4d86-9884-32865cc8ca9d)
