### ISSUE TITLE
Let users configure sparsity detector and coloring algorithm

### ISSUE THREAD

**Issue by gdalle** [JuliaSmoothOptimizers/ADNLPModels.jl#242]
See the discussion in https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/pull/230#issuecomment-2151461371

**Comment by amontoison** [comment]
It's already the case. It's a keyword augment of `SparseADHessian` and `SparseADJacobian`.
https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/blob/main/src/sparse_hessian.jl#L24

**Comment by gdalle** [comment]
Where is it documented? Can't find those in the API reference

**Comment by gdalle** [comment]
If it's not documented, users can't know where to change it

**Comment by gdalle** [comment]
Same goes for the coloring algorithm since #244

**Comment by amontoison** [comment]
Let's update everything after that we switch to `DifferentiationInterface.jl`.

**Comment by gdalle** [comment]
Roadmap:

1. Track down where we inserted the sparsity detector and coloring algorithms in PRs #230 and #244
2. Tell users how they can change it

**Comment by amontoison** [comment]
@gdalle I'm wondering if we could not use a `symmetric_coloring` before rely we rely on DI.jl.
We probably just need to update https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/blob/main/src/sparse_hessian.jl#L208-L216.

**Comment by gdalle** [comment]
Yes you can, I outlined how to do it in #246.
