### ISSUE TITLE
CI allow failure on nightly

### ISSUE THREAD

**Issue by tmigot** [JuliaSmoothOptimizers/ADNLPModels.jl#266]
Since this package constantly depend on cutting-edge AD packages, it will very often fail on the nightly anyway.
what do you think @amontoison ?

**Comment by amontoison** [comment]
I propose to remove nightly builds.

**Comment by tmigot** [comment]
It is still useful information, no?

**Comment by amontoison** [comment]
Not with Zygote :)
I propose to remove it for now and add it again when we will rely on DI.jl.

**Comment by tmigot** [comment]
I think it helps us having a grasp of what packages are breaking forever or what packages are making big changes (like Enzyme is sometimes breaking on the nightly but that's still under heavy dev'). Also some users may ask questions about using ADNLPModels under the nightly in which case I prefer to be aware of potential issues.

**Comment by amontoison** [comment]
We now use buildkite for Enzyme and Zygote. We can keep builds on nightly for the package without optional dependencies.
