### ISSUE TITLE
Breakage OptimalControl.jl: `ct-registry` no more needed

### ISSUE THREAD

**Issue by ocots** [JuliaSmoothOptimizers/ADNLPModels.jl#298]
This line is useless now since OptimalControl.jl is now in the General registry:

https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/blob/b2274e1b81b36752754a68b3f04c27358a3e6495/.github/workflows/Breakage.yml#L60

**Comment by ocots** [comment]
I try a PR :-)

**Comment by amontoison** [comment]
done #299
