### ISSUE TITLE
Fix multiprecision test - wrong string is being used

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/ADNLPModels.jl#36]
Here:
https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/blob/1ade46907a1aa2d538c9298bd84fd5ea1adc9fbc/test/nlp/nlpmodelstest.jl#L19

`problem` is 
https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/blob/1ade46907a1aa2d538c9298bd84fd5ea1adc9fbc/test/nlp/nlpmodelstest.jl#L3

It should be
https://github.com/JuliaSmoothOptimizers/ADNLPModels.jl/blob/1ade46907a1aa2d538c9298bd84fd5ea1adc9fbc/test/nlp/nlpmodelstest.jl#L5

**Comment by tmigot** [comment]
Actually, the input of `multiple_precision_nlp` should probably be an array of functions such that T::DataType -> AbstractNLPModel instead of taking an array of `String`.
What do you think?
