### ISSUE TITLE
Use in place functions by default for constraints and residuals

### ISSUE THREAD

**Issue by abelsiqueira** [JuliaSmoothOptimizers/ADNLPModels.jl#47]

**Comment by tmigot** [comment]
I am trying to think how to do this.
Should we make a breaking change and force the usage of `c!`? The drawback is that it is less convenient for users that don't usually provide such function.
The alternative is to provide a different constructor I guess.

**Comment by dpo** [comment]
It's difficult to do in general: https://github.com/dpo/ReverseADNLSModels
Example of the difficulty: https://github.com/dpo/ReverseADNLSModels/blob/main/benchmarks/benchmark.jl#L39

Even what's in there doesn't work in all cases. Zygote doesn't seem to support in-place operations, so we have to use ReverseDiff, which hasn't been updated in quite a while. I suggest we focus on in-place functions later. We can use my other repo as a playground to bounce ideas around and test strategies.

**Comment by tmigot** [comment]
I see, it is not trivial indeed. Actually, a solution might be to have another structure `IADNLPModel` for in-place ADNLPModel that takes in-place `c` and `F` only.

**Comment by dpo** [comment]
That's basically what I did for F. c would be the same.

**Comment by tmigot** [comment]
Close in #104 and #101
